import { useEffect, useState } from 'react'
import { api } from '../../api'
import { formatMoney } from '../../data/services'
import { formatDate, PAYMENT_LABELS, PROJECT_LABELS } from './adminConstants'
import './AdminCrudPages.css'

function useList(path, token) {
  const [state, setState] = useState({ data: null, loading: true, error: '' }), [version, setVersion] = useState(0)
  useEffect(() => { let active = true; setState((old) => ({ ...old, loading: true, error: '' })); api(path, { token }).then((data) => active && setState({ data, loading: false, error: '' })).catch((error) => active && setState({ data: null, loading: false, error: error.message })); return () => { active = false } }, [path, token, version])
  return { ...state, refresh: () => setVersion((value) => value + 1) }
}
function useDebouncedValue(value, delay = 300) {
  const [debounced, setDebounced] = useState(value)
  useEffect(() => { const timeout = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(timeout) }, [delay, value])
  return debounced
}
const Empty = ({ text }) => <div className="admin-empty"><span>◇</span><h3>Chưa có dữ liệu</h3><p>{text}</p></div>
const Message = ({ value }) => value && <p className={`admin-crud-message${value.type === 'error' ? ' error' : ''}`}>{value.text}</p>

function Modal({ title, onClose, children }) {
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = previous } }, [])
  return <div className="admin-modal-layer"><button className="admin-modal-backdrop" onClick={onClose} aria-label="Đóng" /><section className="admin-modal"><div className="admin-modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</section></div>
}

const packageInitial = { name: '', slug: '', description: '', price: '', features: '', displayOrder: 0, isActive: true }
export function PackageManager({ token, actionRef }) {
  const { data, loading, error, refresh } = useList('/admin/packages', token), [editing, setEditing] = useState(null), [form, setForm] = useState(packageInitial), [message, setMessage] = useState(null)
  useEffect(() => { if (actionRef) actionRef.current = () => { setEditing('new'); setForm(packageInitial) } }, [actionRef])
  const open = (item) => { setEditing(item.id); setForm({ ...item, features: item.features.join('\n') }) }
  const submit = async (event) => { event.preventDefault(); setMessage(null); try { await api(editing === 'new' ? '/admin/packages' : `/admin/packages/${editing}`, { method: editing === 'new' ? 'POST' : 'PATCH', token, body: { ...form, price: Number(form.price), displayOrder: Number(form.displayOrder), features: form.features.split('\n').filter(Boolean) } }); setEditing(null); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const toggle = async (id) => { try { await api(`/admin/packages/${id}/toggle-active`, { method: 'PATCH', token }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading) return <div className="admin-loading">Đang tải gói dịch vụ…</div>; if (error) return <div className="admin-error">{error}</div>
  return <><Message value={message} /><div className="admin-card-grid">{data.packages.map((item) => <article className="admin-data-card" key={item.id}><div><span className={`admin-active-dot${item.isActive ? ' active' : ''}`} />{item.isActive ? 'Đang hoạt động' : 'Đã tắt'} · Thứ tự {item.displayOrder}</div><h2>{item.name}</h2><strong>{formatMoney(item.price)}</strong><p>{item.description}</p><ul>{item.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><div className="admin-card-actions"><button onClick={() => open(item)}>Sửa gói</button><button onClick={() => toggle(item.id)}>{item.isActive ? 'Tắt gói' : 'Bật gói'}</button></div></article>)}</div>{editing && <Modal title={editing === 'new' ? 'Thêm gói mới' : 'Sửa gói dịch vụ'} onClose={() => setEditing(null)}><form className="admin-crud-form" onSubmit={submit}><label>Tên gói<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Slug<input required value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} /></label><label>Giá gói<input required type="number" min="0" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></label><label>Thứ tự hiển thị<input type="number" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} /></label><label className="full">Mô tả<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="full">Tính năng — mỗi dòng một mục<textarea required value={form.features} onChange={(e) => setForm({ ...form, features: e.target.value })} /></label><Message value={message} /><div className="admin-form-actions"><button type="button" onClick={() => setEditing(null)}>Hủy</button><button className="button">Lưu gói</button></div></form></Modal>}</>
}

const promoInitial = { code: '', description: '', discountType: 'PERCENT', discountValue: '', usageLimit: '', startsAt: '', expiresAt: '', isActive: true }
const dateInput = (value) => value ? new Date(value).toISOString().slice(0, 10) : ''
export function PromoManager({ token, actionRef }) {
  const { data, loading, error, refresh } = useList('/admin/promo-codes', token), [editing, setEditing] = useState(null), [form, setForm] = useState(promoInitial), [message, setMessage] = useState(null)
  useEffect(() => { if (actionRef) actionRef.current = () => { setEditing('new'); setForm(promoInitial) } }, [actionRef])
  const open = (item) => { setEditing(item.id); setForm({ ...item, startsAt: dateInput(item.startsAt), expiresAt: dateInput(item.expiresAt), usageLimit: item.usageLimit ?? '' }) }
  const submit = async (event) => { event.preventDefault(); setMessage(null); try { await api(editing === 'new' ? '/admin/promo-codes' : `/admin/promo-codes/${editing}`, { method: editing === 'new' ? 'POST' : 'PATCH', token, body: { ...form, discountValue: Number(form.discountValue), usageLimit: form.usageLimit === '' ? null : Number(form.usageLimit), startsAt: form.startsAt || null, expiresAt: form.expiresAt || null } }); setEditing(null); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const toggle = async (id) => { try { setMessage(null); await api(`/admin/promo-codes/${id}/toggle-active`, { method: 'PATCH', token }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading) return <div className="admin-loading">Đang tải mã khuyến mãi…</div>; if (error) return <div className="admin-error">{error}</div>
  return <><div className="admin-card-grid">{data.promoCodes.map((item) => <article className="admin-data-card promo" key={item.id}><div><span className={`admin-active-dot${item.isActive ? ' active' : ''}`} />{item.isActive ? 'Đang hoạt động' : 'Đã tắt'}</div><h2>{item.code}</h2><strong>{item.discountType === 'PERCENT' ? `${item.discountValue}%` : formatMoney(item.discountValue)}</strong><p>{item.description}</p><small>Đã dùng <b>{item.usedCount}</b>{item.usageLimit ? ` / ${item.usageLimit}` : ''} lần · Hết hạn: {item.expiresAt ? formatDate(item.expiresAt) : 'Không giới hạn'}</small><div className="admin-card-actions"><button onClick={() => open(item)}>Sửa mã</button><button onClick={() => toggle(item.id)}>{item.isActive ? 'Tắt mã' : 'Bật mã'}</button></div></article>)}</div>{editing && <Modal title={editing === 'new' ? 'Thêm mã khuyến mãi' : 'Sửa mã khuyến mãi'} onClose={() => setEditing(null)}><form className="admin-crud-form" onSubmit={submit}><label>Mã<input required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} /></label><label>Loại giảm<select value={form.discountType} onChange={(e) => setForm({ ...form, discountType: e.target.value })}><option value="PERCENT">Phần trăm</option><option value="FIXED">Số tiền cố định</option></select></label><label>Giá trị giảm<input required type="number" min="1" value={form.discountValue} onChange={(e) => setForm({ ...form, discountValue: e.target.value })} /></label><label>Giới hạn sử dụng<input type="number" min="1" value={form.usageLimit} onChange={(e) => setForm({ ...form, usageLimit: e.target.value })} placeholder="Không giới hạn" /></label><label>Bắt đầu<input type="date" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /></label><label>Hết hạn<input type="date" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /></label><label className="full">Mô tả<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><Message value={message} /><div className="admin-form-actions"><button type="button" onClick={() => setEditing(null)}>Hủy</button><button className="button">Lưu mã</button></div></form></Modal>}</>
}

export function CustomerManager({ token }) {
  const [search, setSearch] = useState(''), [selected, setSelected] = useState(null), [form, setForm] = useState({ name: '', phone: '' }), [orders, setOrders] = useState([]), [message, setMessage] = useState(null)
  const debouncedSearch = useDebouncedValue(search)
  const { data, loading, error, refresh } = useList(`/admin/customers?search=${encodeURIComponent(debouncedSearch)}`, token)
  const open = async (customer) => { setSelected(customer); setForm({ name: customer.name, phone: customer.phone }); try { const result = await api(`/admin/customers/${customer.id}/orders`, { token }); setOrders(result.orders) } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const save = async () => { try { const result = await api(`/admin/customers/${selected.id}`, { method: 'PATCH', token, body: form }); setSelected({ ...selected, ...result.customer }); refresh(); setMessage({ text: 'Đã cập nhật khách hàng.' }) } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const toggle = async (customer) => { try { setMessage(null); await api(`/admin/customers/${customer.id}/toggle-active`, { method: 'PATCH', token }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading) return <div className="admin-loading">Đang tải khách hàng…</div>; if (error) return <div className="admin-error">{error}</div>
  return <><div className="admin-filters"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm theo tên, email, điện thoại…" /></div><section className="admin-panel">{data.customers.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Khách hàng</th><th>Email</th><th>Điện thoại</th><th>Số đơn</th><th>Tổng giá trị</th><th>Trạng thái</th><th /></tr></thead><tbody>{data.customers.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.email}</td><td>{item.phone}</td><td>{item.orderCount}</td><td>{formatMoney(item.totalOrderValue)}</td><td>{item.isActive ? 'Đang hoạt động' : 'Đã khóa'}</td><td><button className="admin-row-action" onClick={() => open(item)}>Chi tiết →</button><button className="admin-row-action danger" onClick={() => toggle(item)}>{item.isActive ? 'Khóa' : 'Mở'}</button></td></tr>)}</tbody></table></div> : <Empty text="Khách hàng đăng ký sẽ xuất hiện tại đây." />}</section>{selected && <Modal title="Chi tiết khách hàng" onClose={() => setSelected(null)}><div className="admin-customer-summary"><p><span>Email</span><strong>{selected.email}</strong></p><p><span>Tổng giá trị đơn</span><strong>{formatMoney(selected.totalOrderValue)}</strong></p></div><div className="admin-crud-form"><label>Họ tên<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Điện thoại<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><button className="button" onClick={save}>Lưu thông tin</button><Message value={message} /></div><h3 className="admin-modal-section-title">Lịch sử đơn dịch vụ</h3>{orders.length ? orders.map((order) => <div className="admin-mini-order" key={order.id}><span>#{order.id.slice(-8).toUpperCase()} · {order.packageName}</span><strong>{formatMoney(order.finalPrice)} · {PAYMENT_LABELS[order.paymentStatus]}</strong></div>) : <p>Khách hàng chưa có đơn.</p>}</Modal>}</>
}

export function BriefManager({ token }) {
  const { data, loading, error, refresh } = useList('/admin/briefs', token), [selected, setSelected] = useState(null), [note, setNote] = useState(''), [message, setMessage] = useState(null)
  const open = (brief) => { setSelected(brief); setNote(brief.adminBriefNote || '') }
  const review = async () => { try { setMessage(null); await api(`/admin/briefs/${selected.id}/review`, { method: 'PATCH', token, body: { isReviewed: !selected.isReviewed } }); setSelected({ ...selected, isReviewed: !selected.isReviewed }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const saveNote = async () => { try { await api(`/admin/briefs/${selected.id}/note`, { method: 'PATCH', token, body: { adminBriefNote: note } }); setMessage({ text: 'Đã lưu ghi chú brief.' }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading) return <div className="admin-loading">Đang tải brief…</div>; if (error) return <div className="admin-error">{error}</div>
  return <><section className="admin-panel">{data.briefs.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Khách hàng</th><th>Doanh nghiệp</th><th>Lĩnh vực</th><th>Gói</th><th>Review</th><th>Trạng thái</th><th /></tr></thead><tbody>{data.briefs.map((brief) => <tr key={brief.id}><td>{brief.order.customer.name}</td><td><strong>{brief.businessName}</strong></td><td>{brief.businessType}</td><td>{brief.order.packageName}</td><td>{brief.isReviewed ? 'Đã review' : 'Chưa review'}</td><td>{PROJECT_LABELS[brief.order.projectStatus]}</td><td><button className="admin-row-action" onClick={() => open(brief)}>Xử lý →</button></td></tr>)}</tbody></table></div> : <Empty text="Brief khách hàng gửi sẽ xuất hiện tại đây." />}</section>{selected && <Modal title={`Brief · ${selected.businessName}`} onClose={() => setSelected(null)}><div className="admin-brief-view"><p><span>Mục tiêu website</span>{selected.websiteGoal}</p><p><span>Mô tả dự án</span>{selected.projectDescription}</p><p><span>Phong cách</span>{selected.preferredStyle || '—'}</p><p><span>Website tham khảo</span>{selected.referenceWebsite || '—'}</p><p><span>Ghi chú khách hàng</span>{selected.customerNote || '—'}</p></div><label className="admin-standalone-field">Ghi chú xử lý<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><Message value={message} /><div className="admin-form-actions"><button onClick={review}>{selected.isReviewed ? 'Đánh dấu chưa review' : 'Đánh dấu đã review'}</button><button className="button" onClick={saveNote}>Lưu ghi chú</button></div></Modal>}</>
}

const faqInitial = { question: '', answer: '', category: 'Chung', displayOrder: 0, isActive: true }
export function FaqManager({ token, actionRef }) {
  const { data, loading, error, refresh } = useList('/admin/faqs', token), [editing, setEditing] = useState(null), [form, setForm] = useState(faqInitial), [message, setMessage] = useState(null)
  useEffect(() => { if (actionRef) actionRef.current = () => { setEditing('new'); setForm(faqInitial) } }, [actionRef])
  const submit = async (event) => { event.preventDefault(); try { await api(editing === 'new' ? '/admin/faqs' : `/admin/faqs/${editing}`, { method: editing === 'new' ? 'POST' : 'PATCH', token, body: { ...form, displayOrder: Number(form.displayOrder) } }); setEditing(null); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  const toggle = async (id) => { try { setMessage(null); await api(`/admin/faqs/${id}/toggle-active`, { method: 'PATCH', token }); refresh() } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading) return <div className="admin-loading">Đang tải FAQ…</div>; if (error) return <div className="admin-error">{error}</div>
  return <><div className="admin-faq-list">{data.faqs.map((faq) => <article className="admin-panel" key={faq.id}><div><span className={`admin-active-dot${faq.isActive ? ' active' : ''}`} /> {faq.category} · Thứ tự {faq.displayOrder}</div><h3>{faq.question}</h3><p>{faq.answer}</p><div className="admin-card-actions"><button onClick={() => { setEditing(faq.id); setForm(faq) }}>Sửa</button><button onClick={() => toggle(faq.id)}>{faq.isActive ? 'Tắt' : 'Bật'}</button></div></article>)}</div>{editing && <Modal title={editing === 'new' ? 'Thêm FAQ' : 'Sửa FAQ'} onClose={() => setEditing(null)}><form className="admin-crud-form" onSubmit={submit}><label className="full">Câu hỏi<input required value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} /></label><label className="full">Câu trả lời<textarea required value={form.answer} onChange={(e) => setForm({ ...form, answer: e.target.value })} /></label><label>Danh mục<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Thứ tự<input type="number" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} /></label><Message value={message} /><div className="admin-form-actions"><button type="button" onClick={() => setEditing(null)}>Hủy</button><button className="button">Lưu FAQ</button></div></form></Modal>}</>
}

export function SettingsManager({ token }) {
  const { data, loading, error } = useList('/admin/settings', token), [form, setForm] = useState(null), [message, setMessage] = useState(null)
  useEffect(() => { if (data?.settings) setForm(data.settings) }, [data])
  const save = async (event) => { event.preventDefault(); try { const result = await api('/admin/settings', { method: 'PATCH', token, body: form }); setForm(result.settings); setMessage({ text: 'Đã cập nhật cài đặt website.' }) } catch (e) { setMessage({ type: 'error', text: e.message }) } }
  if (loading || !form) return <div className="admin-loading">Đang tải cài đặt…</div>; if (error) return <div className="admin-error">{error}</div>
  const field = (name, label, type = 'text') => <label>{label}<input type={type} value={form[name] ?? ''} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></label>
  return <form className="admin-panel admin-settings-form" onSubmit={save}><section><h2>Thông tin thương hiệu</h2>{field('brandName', 'Tên thương hiệu')}{field('tagline', 'Tagline')}<label>Mô tả footer<textarea value={form.footerDescription} onChange={(e) => setForm({ ...form, footerDescription: e.target.value })} /></label></section><section><h2>Liên hệ công khai</h2>{field('contactEmail', 'Email', 'email')}{field('facebookUrl', 'Facebook URL')}{field('zaloUrl', 'Zalo URL')}{field('locationText', 'Khu vực')}</section><section><h2>Thông tin chuyển khoản</h2><p>Chỉ dùng trong luồng thanh toán, không hiển thị ở footer.</p>{field('bankName', 'Ngân hàng')}{field('bankAccountName', 'Chủ tài khoản')}{field('bankAccountNumber', 'Số tài khoản')}</section><Message value={message} /><button className="button">Lưu cài đặt</button></form>
}
