import { useEffect, useState } from 'react'
import { api } from '../api'
import { formatMoney } from '../data/services'
import PriceSummary from './PriceSummary'
import './Dashboards.css'

const paymentStatuses = { UNPAID: 'Chưa thanh toán', DEPOSIT_PENDING: 'Chờ thanh toán cọc', DEPOSIT_PAID: 'Đã thanh toán cọc', FINAL_PAYMENT_PENDING: 'Chờ thanh toán cuối', FULLY_PAID: 'Đã thanh toán đủ', CANCELLED: 'Đã hủy' }
const projectStatuses = { WAITING_DEPOSIT: 'Chờ cọc', WAITING_BRIEF: 'Chờ brief', BRIEF_SUBMITTED: 'Đã gửi brief', REVIEWING: 'Đang xem xét', IN_PROGRESS: 'Đang thực hiện', WAITING_FEEDBACK: 'Chờ phản hồi', WAITING_FINAL_PAYMENT: 'Chờ thanh toán cuối', READY_TO_DELIVER: 'Sẵn sàng bàn giao', COMPLETED: 'Hoàn thành', CANCELLED: 'Đã hủy' }
const statusOptions = (items) => Object.entries(items).map(([value, label]) => <option value={value} key={value}>{label}</option>)
const Empty = ({ onHome }) => <div className="empty-state"><h2>Chưa có đơn dịch vụ</h2><p>Chọn một gói dịch vụ để bắt đầu.</p><button className="button" onClick={onHome}>Xem gói dịch vụ</button></div>

export function CustomerDashboard({ token, user, notice, onHome, onBrief, onLogout }) {
  const [orders, setOrders] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  useEffect(() => { api('/orders/my', { token }).then((data) => setOrders(data.orders)).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [token])
  return <main className="dashboard-page"><div className="container dashboard-shell"><div className="dashboard-heading"><div><p className="eyebrow">Khách hàng · {user.name}</p><h1>Dự án của tôi</h1></div><div className="dashboard-actions"><button className="button button-secondary" onClick={onLogout}>Đăng xuất</button><button className="button" onClick={onHome}>Đặt thêm dịch vụ</button></div></div>{notice && <div className="payment-notice"><strong>Đơn dịch vụ đã được tạo.</strong><span>{notice}</span></div>}{error && <p className="form-message error">{error}</p>}{loading ? <p>Đang tải đơn dịch vụ…</p> : !orders.length ? <Empty onHome={onHome} /> : <div className="customer-order-list">{orders.map((order) => <article className="dashboard-card customer-card" key={order.id}><div className="order-card-head"><div><span className="order-id">#{order.id.slice(-8).toUpperCase()}</span><h2>{order.packageName}</h2></div><span className="status pending">{paymentStatuses[order.paymentStatus]}</span></div><div className="customer-metrics"><div><span>Giá sau giảm</span><strong>{formatMoney(order.finalPrice)}</strong></div><div><span>Cọc 30%</span><strong>{formatMoney(order.depositAmount)}</strong></div><div><span>Còn lại 70%</span><strong>{formatMoney(order.remainingAmount)}</strong></div></div><div className="status-row"><span>Trạng thái thanh toán <strong>{paymentStatuses[order.paymentStatus]}</strong></span><span>Trạng thái dự án <strong>{projectStatuses[order.projectStatus]}</strong></span></div><button className="button button-secondary brief-button" onClick={() => onBrief(order)}>Brief dự án</button></article>)}</div>}</div></main>
}

function AdminOrderCard({ order, token, onChanged }) {
  const [note, setNote] = useState(order.adminNote || ''), [detail, setDetail] = useState(null), [error, setError] = useState('')
  const patch = async (path, body) => { try { const data = await api(`/admin/orders/${order.id}/${path}`, { method: 'PATCH', token, body }); onChanged(data.order) } catch (e) { setError(e.message) } }
  const showDetail = async () => { try { setDetail((await api(`/admin/orders/${order.id}`, { token })).brief || { empty: true }) } catch (e) { setError(e.message) } }
  return <article className="dashboard-card admin-card"><div className="order-card-head"><div><span className="order-id">#{order.id.slice(-8).toUpperCase()}</span><h2>{order.packageName}</h2><p>{order.customer?.name} · {order.customer?.email} · {order.customer?.phone}</p></div><span className="status pending">{paymentStatuses[order.paymentStatus]}</span></div><PriceSummary pricing={order} compact /><div className="admin-controls"><label>Trạng thái thanh toán<select value={order.paymentStatus} onChange={(e) => patch('payment-status', { paymentStatus: e.target.value })}>{statusOptions(paymentStatuses)}</select></label><label>Trạng thái dự án<select value={order.projectStatus} onChange={(e) => patch('project-status', { projectStatus: e.target.value })}>{statusOptions(projectStatuses)}</select></label><label className="full">Ghi chú nội bộ<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><div className="admin-buttons"><button className="button button-secondary" onClick={showDetail}>Xem brief</button><button className="button" onClick={() => patch('note', { adminNote: note })}>Lưu ghi chú</button></div></div>{detail && <div className="brief-detail">{detail.empty ? <p>Khách hàng chưa gửi brief.</p> : <><h3>{detail.businessName}</h3><p><strong>Lĩnh vực:</strong> {detail.businessType}</p><p><strong>Mục tiêu:</strong> {detail.websiteGoal}</p><p><strong>Mô tả:</strong> {detail.projectDescription}</p><p><strong>Phong cách:</strong> {detail.preferredStyle || '—'}</p><p><strong>Website tham khảo:</strong> {detail.referenceWebsite || '—'}</p><p><strong>Thời gian:</strong> {detail.timeline || '—'}</p><p><strong>Tài nguyên:</strong> {detail.hasLogo ? 'Đã có logo' : 'Chưa có logo'} · {detail.hasContentReady ? 'Đã có nội dung' : 'Chưa có nội dung'}</p><p><strong>Ghi chú khách hàng:</strong> {detail.customerNote || '—'}</p></>}</div>}{error && <p className="form-message error">{error}</p>}</article>
}

export function AdminDashboard({ token, user, onHome, onLogout }) {
  const [orders, setOrders] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  useEffect(() => { api('/admin/orders', { token }).then((data) => setOrders(data.orders)).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [token])
  const changed = (updated) => setOrders((items) => items.map((item) => item.id === updated.id ? { ...item, ...updated, customer: item.customer, servicePackage: item.servicePackage } : item))
  return <main className="dashboard-page"><div className="container dashboard-shell"><div className="dashboard-heading"><div><p className="eyebrow">Quản trị · {user.name}</p><h1>Quản lý đơn dịch vụ</h1></div><div className="dashboard-actions"><button className="button button-secondary" onClick={onLogout}>Đăng xuất</button><button className="button" onClick={onHome}>Trang chủ</button></div></div>{error && <p className="form-message error">{error}</p>}{loading ? <p>Đang tải đơn dịch vụ…</p> : !orders.length ? <Empty onHome={onHome} /> : <div className="admin-order-list">{orders.map((order) => <AdminOrderCard key={order.id} order={order} token={token} onChanged={changed} />)}</div>}</div></main>
}
